### Ajouter un user
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Maurice",
    "email": "lucile.dufour@mail.fr",
    "password": "luciledu59"
}

### Auth user
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "lucile.dufour@mail.fr",
    "password": "luciledu59"
}

### test authorization
GET http://localhost:3000/test
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNCwicm9sZSI6InVzZXIifSwiaWF0IjoxNjIzMzU4NTYwLCJleHAiOjE2MjMzNzI5NjB9.xsxG-eJfQDZ8nNHGVqtuXtfjZUiPlZho7BviJ52sJAs
Content-Type: application/json

{
}