### Ajouter un user
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Louis",
    "email": "louis.dufour@mail.fr",
    "password": "louloudu31"

}

### Auth user
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "megamartin.dufour@mail.com",
    "password": "martinmega74"
}


### recherche d'annonces
GET http://localhost:3000/search
Content-Type: application/json

{
    "title": "échelle",
    "postcode": "12000",
    "radius": "0"
}

### Données user
GET http://localhost:3000/account/settings
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjYsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTYyMzY2MDQzNCwiZXhwIjoxNjIzNjc0ODM0fQ.bIymsJE9Suvm3Qdu3jScs_NfkTzIoRMZIATZ_VVcDC8
Content-Type: application/json

{
}

### Update Données user
PATCH  http://localhost:3000/account/settings
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjgsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTYyMzY3NDk2NywiZXhwIjoxNjIzNjg5MzY3fQ.WgtTnQlpv_d8MSydyHWSR4JfJUsU8NEqhDFk4xwCaew
Content-Type: application/json

{
    "name": "demonteP",
    "email": "megamartin.dufour@mail.com",
    "phone": "0625986319"
}

### Update password user
PATCH  http://localhost:3000/account/settings/password
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjYsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTYyMzY2MDQzNCwiZXhwIjoxNjIzNjc0ODM0fQ.bIymsJE9Suvm3Qdu3jScs_NfkTzIoRMZIATZ_VVcDC8
Content-Type: application/json

{
    "password": "luciledu59",
    "newPassword": "martinmega74"
}

### Delete user account
DELETE http://localhost:3000/account/settings 
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjcsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTYyMzY2OTE1OSwiZXhwIjoxNjIzNjgzNTU5fQ.cel60z7WyQl6O2ZtjOhLXrUCwlifdclmXuD2b1wuzcA
Content-Type: application/json

{

}